import { parseWebPublicEnvironment, type WebPublicEnvironment } from '@mustbeviral/config';

export function readWebPublicEnvironment(
  source: Readonly<Record<string, string | undefined>> = {
    NEXT_PUBLIC_APP_ORIGIN: process.env.NEXT_PUBLIC_APP_ORIGIN,
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,
    NEXT_PUBLIC_CORE_API_URL: process.env.NEXT_PUBLIC_CORE_API_URL,
    NEXT_PUBLIC_COLLABORATION_API_URL: process.env.NEXT_PUBLIC_COLLABORATION_API_URL,
  },
): WebPublicEnvironment {
  return parseWebPublicEnvironment({
    NEXT_PUBLIC_APP_ORIGIN: source.NEXT_PUBLIC_APP_ORIGIN,
    NEXT_PUBLIC_SUPABASE_URL: source.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: source.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,
    NEXT_PUBLIC_CORE_API_URL: source.NEXT_PUBLIC_CORE_API_URL,
    NEXT_PUBLIC_COLLABORATION_API_URL: source.NEXT_PUBLIC_COLLABORATION_API_URL,
  });
}
