export const REQUIRED_TABLES = [
	"users",
	"password_credentials",
	"sessions",
	"oauth_accounts",
	"workspaces",
	"workspace_members",
	"invitations",
	"brands",
	"brand_social_profiles",
	"brand_profile_versions",
	"brand_assets",
	"website_scans",
	"social_scans",
	"competitor_scans",
	"marketing_scores",
	"target_market_reports",
	"campaigns",
	"content_calendars",
	"content_posts",
	"post_variants",
	"generated_creatives",
	"approvals",
	"scheduled_posts",
	"dm_rules",
	"dm_events",
	"analytics_snapshots",
	"weekly_reports",
	"growth_opportunities",
	"agent_runs",
	"workflow_runs",
	"usage_events",
	"subscriptions",
	"webhooks_inbox",
	"idempotency_keys",
	"audit_logs",
	"creator_profiles",
	"marketplace_matches",
] as const;

export type RequiredTable = (typeof REQUIRED_TABLES)[number];

export const STATUS_ENUMS = {
	userRole: ["user", "admin"],
	workspacePlan: ["starter", "growth", "agency", "managed"],
	memberRole: ["owner", "admin", "member"],
	brandStatus: ["active", "paused", "archived"],
	onboardingStatus: ["not_started", "running", "complete", "failed"],
	postStatus: [
		"draft",
		"pending_approval",
		"approved",
		"rejected",
		"scheduled",
		"published",
		"failed",
	],
	approvalAction: ["approve", "reject", "edit", "regenerate"],
	scheduledPostStatus: ["pending", "scheduled", "published", "failed", "manual_export"],
	dmRuleStatus: ["draft", "pending_approval", "approved", "active", "paused", "rejected"],
	workflowStatus: ["queued", "running", "complete", "failed", "waiting_manual"],
	subscriptionStatus: ["trialing", "active", "past_due", "canceled", "incomplete"],
	webhookStatus: ["received", "processed", "failed", "ignored"],
} as const;
