import { listRepositoryFiles, readJson, readText, readYaml, writeAtomic } from './lib.mjs';

function markdownDocument(id, heading, body) {
  return `---\ndoc_id: ${id}\n---\n\n# ${heading}\n\n${body.trim()}\n`;
}

function buildIndex(manifest) {
  const rows = manifest.documents
    .filter((document) => document.path !== 'docs/INDEX.md')
    .map(
      (document) =>
        `| \`${document.id}\` | [${document.path.replace('docs/', '')}](./${document.path.replace('docs/', '')}) | ${document.kind} | ${document.status} | ${document.owner} |`,
    )
    .join('\n');
  return markdownDocument(
    'docs-index',
    'MustBeViral Studio authority index',
    `DO NOT EDIT — generated from \`docs/MANIFEST.yaml\`.\n\nStart with root \`AGENTS.md\`, run \`pnpm agent:preflight\`, and follow the one active packet. \`PROJECT_STATE.yaml\` owns current state; this index only maps registered authority.\n\n| Document ID | Path | Kind | Status | Owner |\n|---|---|---|---|---|\n${rows}`,
  );
}

function buildStatus(state, packet) {
  const blockers = state.blockers.length ? state.blockers.join('; ') : 'None';
  const decisions = state.decisions_pending.length ? state.decisions_pending.join('; ') : 'None';
  return markdownDocument(
    'project-status',
    'Current status',
    `DO NOT EDIT — generated from \`PROJECT_STATE.yaml\` and the active packet.\n\n| Field | Value |\n|---|---|\n| Product | ${state.product_name} |\n| Engine | ${state.internal_engine_name} |\n| Generation | \`${state.generation}\` |\n| Launch customer | \`${state.launch_customer}\` |\n| Phase | ${state.phase.id} — ${state.phase.title} (${state.phase.state}) |\n| Active packet | \`${packet.id}\` |\n| Current step | \`${packet.handoff.current_step}\` |\n| Release target | \`${state.release_target}\` |\n| Pending decisions | ${decisions} |\n| Blockers | ${blockers} |\n| Remote destructive action | \`${state.legacy.destructive_remote_action}\` |\n\n## One next action\n\n${packet.handoff.next_action}`,
  );
}

function buildLlms(state, packet) {
  return `# DO NOT EDIT: generated by \`pnpm docs:generate\`.\n\nproject: ${state.product_name}\nengine: ${state.internal_engine_name}\ngeneration: ${state.generation}\nlaunch_customer: ${state.launch_customer}\nphase: ${state.phase.id}\nactive_packet: ${packet.id}\ncurrent_step: ${packet.handoff.current_step}\nnext_action: ${packet.handoff.next_action}\nagent_protocol: AGENTS.md\ncurrent_state: PROJECT_STATE.yaml\ndocumentation_index: docs/INDEX.md\nauthority_manifest: docs/MANIFEST.yaml\nactive_work_packet: docs/delivery/ACTIVE_WORK_PACKET.yaml\n`;
}

function buildOpenApiReference() {
  const sourcePath = 'packages/contracts/openapi/core.v1.json';
  const contract = readJson(sourcePath);
  const routes = Object.entries(contract.paths)
    .flatMap(([route, operations]) =>
      Object.entries(operations).map(
        ([method, operation]) =>
          `| \`${method.toUpperCase()}\` | \`${route}\` | \`${operation.operationId}\` | ${operation.summary} |`,
      ),
    )
    .join('\n');
  const schemas = Object.keys(contract.components.schemas)
    .sort()
    .map((schema) => `\`${schema}\``)
    .join(', ');
  return markdownDocument(
    'generated-openapi',
    'DO NOT EDIT — Generated OpenAPI reference',
    `Source: \`${sourcePath}\` (OpenAPI ${contract.openapi}, contract ${contract.info.version}).\n\n| Method | Path | Operation | Contract |\n|---|---|---|---|\n${routes}\n\nSchemas: ${schemas}.`,
  );
}

function buildDatabaseReference() {
  const migrations = listRepositoryFiles(['supabase/migrations/*.sql']).sort();
  const objects = migrations.flatMap((migration) => {
    const sql = readText(migration);
    const schemas = [
      ...sql.matchAll(/create\s+schema\s+(?:if\s+not\s+exists\s+)?([a-z_][a-z0-9_]*)/gi),
    ].map((match) => `schema \`${match[1]}\``);
    const tables = [
      ...sql.matchAll(/create\s+table\s+(?:if\s+not\s+exists\s+)?([a-z_.][a-z0-9_.]*)/gi),
    ].map((match) => `table \`${match[1]}\``);
    return [...schemas, ...tables].map((object) => `| \`${migration}\` | ${object} |`);
  });
  const rows = objects.length ? objects.join('\n') : '| — | No durable objects implemented |';
  return markdownDocument(
    'generated-database-schema',
    'DO NOT EDIT — Generated database schema reference',
    `Sources: ordered raw SQL under \`supabase/migrations\`. Generated Supabase types become an additional source after the first product schema lands.\n\n| Migration | Implemented object |\n|---|---|\n${rows}`,
  );
}

function buildEnvironmentReference() {
  const sourcePath = 'packages/config/environment.manifest.json';
  const manifest = readJson(sourcePath);
  const rows = manifest.variables
    .map(
      (variable) =>
        `| \`${variable.name}\` | ${variable.owner} | ${variable.environments.join(', ')} | ${variable.sensitivity} | ${variable.required ? 'yes' : 'no'} | ${variable.description} |`,
    )
    .join('\n');
  return markdownDocument(
    'generated-environment',
    'DO NOT EDIT — Generated environment reference',
    `Source: \`${sourcePath}\`. Values are intentionally excluded.\n\n| Variable | Owner | Environments | Sensitivity | Required | Purpose |\n|---|---|---|---|---|---|\n${rows}`,
  );
}

function buildGenerated(manifest, state, packet) {
  const topicRows = manifest.documents
    .flatMap((document) =>
      document.authority_topics.map(
        (topic) => `| \`${topic}\` | \`${document.id}\` | ${document.path} |`,
      ),
    )
    .join('\n');
  return {
    'docs/generated/OPENAPI.md': buildOpenApiReference(),
    'docs/generated/DATABASE_SCHEMA.md': buildDatabaseReference(),
    'docs/generated/ENVIRONMENT.md': buildEnvironmentReference(),
    'docs/generated/MODEL_CATALOG.md': markdownDocument(
      'generated-model-catalog',
      'DO NOT EDIT — Generated model catalog',
      'No media model is enabled during R0. A model becomes usable only after capability, price, license, retention, moderation, and evaluation evidence are registered.',
    ),
    'docs/generated/TRACEABILITY.md': markdownDocument(
      'generated-traceability',
      'DO NOT EDIT — Generated traceability reference',
      `Current packet: \`${packet.id}\` (${packet.status}). Current step: \`${packet.handoff.current_step}\`.\n\n| Authority topic | Document | Path |\n|---|---|---|\n${topicRows}`,
    ),
  };
}

export function generatedOutputs() {
  const manifest = readYaml('docs/MANIFEST.yaml');
  const state = readYaml('PROJECT_STATE.yaml');
  const packet = readYaml('docs/delivery/ACTIVE_WORK_PACKET.yaml');
  return {
    'docs/INDEX.md': buildIndex(manifest),
    'docs/STATUS.md': buildStatus(state, packet),
    'llms.txt': buildLlms(state, packet),
    ...buildGenerated(manifest, state, packet),
  };
}

export function generateDocs({ check = false } = {}) {
  const outputs = generatedOutputs();
  const drift = [];
  for (const [relativePath, content] of Object.entries(outputs)) {
    if (check) {
      let current = '';
      try {
        current = readText(relativePath);
      } catch {
        current = '';
      }
      if (current !== content) drift.push(relativePath);
    } else {
      writeAtomic(relativePath, content);
    }
  }
  if (check && drift.length) {
    console.error('Generated documentation drift:');
    for (const file of drift) console.error(`- ${file}`);
    process.exitCode = 1;
  } else if (check) {
    console.log(`Generated documentation is current: ${Object.keys(outputs).length} files.`);
  } else {
    console.log(`Generated documentation updated: ${Object.keys(outputs).length} files.`);
  }
  return drift;
}

if (process.argv[1]?.endsWith('generate-docs.mjs')) {
  generateDocs({ check: process.argv.includes('--check') });
}
