import { readText, readYaml, writeAtomic } from './lib.mjs';

function markdownDocument(id, heading, body) {
  return `---\ndoc_id: ${id}\n---\n\n# ${heading}\n\n${body.trim()}\n`;
}

function buildIndex(manifest) {
  const rows = manifest.documents
    .filter((document) => document.path !== 'docs/INDEX.md')
    .map(
      (document) =>
        `| \`${document.id}\` | [${document.path.replace('docs/', '')}](./${document.path.replace('docs/', '')}) | ${document.kind} | ${document.status} | ${document.owner} |`,
    )
    .join('\n');
  return markdownDocument(
    'docs-index',
    'MustBeViral Studio authority index',
    `DO NOT EDIT — generated from \`docs/MANIFEST.yaml\`.\n\nStart with root \`AGENTS.md\`, run \`pnpm agent:preflight\`, and follow the one active packet. \`PROJECT_STATE.yaml\` owns current state; this index only maps registered authority.\n\n| Document ID | Path | Kind | Status | Owner |\n|---|---|---|---|---|\n${rows}`,
  );
}

function buildStatus(state, packet) {
  const blockers = state.blockers.length ? state.blockers.join('; ') : 'None';
  const decisions = state.decisions_pending.length ? state.decisions_pending.join('; ') : 'None';
  return markdownDocument(
    'project-status',
    'Current status',
    `DO NOT EDIT — generated from \`PROJECT_STATE.yaml\` and the active packet.\n\n| Field | Value |\n|---|---|\n| Product | ${state.product_name} |\n| Engine | ${state.internal_engine_name} |\n| Generation | \`${state.generation}\` |\n| Launch customer | \`${state.launch_customer}\` |\n| Phase | ${state.phase.id} — ${state.phase.title} (${state.phase.state}) |\n| Active packet | \`${packet.id}\` |\n| Current step | \`${packet.handoff.current_step}\` |\n| Release target | \`${state.release_target}\` |\n| Pending decisions | ${decisions} |\n| Blockers | ${blockers} |\n| Remote destructive action | \`${state.legacy.destructive_remote_action}\` |\n\n## One next action\n\n${packet.handoff.next_action}`,
  );
}

function buildLlms(state, packet) {
  return `# DO NOT EDIT: generated by \`pnpm docs:generate\`.\n\nproject: ${state.product_name}\nengine: ${state.internal_engine_name}\ngeneration: ${state.generation}\nlaunch_customer: ${state.launch_customer}\nphase: ${state.phase.id}\nactive_packet: ${packet.id}\ncurrent_step: ${packet.handoff.current_step}\nnext_action: ${packet.handoff.next_action}\nagent_protocol: AGENTS.md\ncurrent_state: PROJECT_STATE.yaml\ndocumentation_index: docs/INDEX.md\nauthority_manifest: docs/MANIFEST.yaml\nactive_work_packet: docs/delivery/ACTIVE_WORK_PACKET.yaml\n`;
}

function buildGenerated(manifest, state, packet) {
  const topicRows = manifest.documents
    .flatMap((document) =>
      document.authority_topics.map(
        (topic) => `| \`${topic}\` | \`${document.id}\` | ${document.path} |`,
      ),
    )
    .join('\n');
  return {
    'docs/generated/OPENAPI.md': markdownDocument(
      'generated-openapi',
      'DO NOT EDIT — Generated OpenAPI reference',
      'No HTTP schemas exist during R0. This file is emitted from registered Zod/OpenAPI contracts when `packages/contracts` is scaffolded.',
    ),
    'docs/generated/DATABASE_SCHEMA.md': markdownDocument(
      'generated-database-schema',
      'DO NOT EDIT — Generated database schema reference',
      'No product migrations exist during R0. This file is emitted from ordered raw SQL migrations and generated Supabase types after the database scaffold exists.',
    ),
    'docs/generated/ENVIRONMENT.md': markdownDocument(
      'generated-environment',
      'DO NOT EDIT — Generated environment reference',
      'No application environment schema exists during R0. This file will list variable names, owners, environments, and sensitivity without exposing values.',
    ),
    'docs/generated/MODEL_CATALOG.md': markdownDocument(
      'generated-model-catalog',
      'DO NOT EDIT — Generated model catalog',
      'No media model is enabled during R0. A model becomes usable only after capability, price, license, retention, moderation, and evaluation evidence are registered.',
    ),
    'docs/generated/TRACEABILITY.md': markdownDocument(
      'generated-traceability',
      'DO NOT EDIT — Generated traceability reference',
      `Current packet: \`${packet.id}\` (${packet.status}). Current step: \`${packet.handoff.current_step}\`.\n\n| Authority topic | Document | Path |\n|---|---|---|\n${topicRows}`,
    ),
  };
}

export function generatedOutputs() {
  const manifest = readYaml('docs/MANIFEST.yaml');
  const state = readYaml('PROJECT_STATE.yaml');
  const packet = readYaml('docs/delivery/ACTIVE_WORK_PACKET.yaml');
  return {
    'docs/INDEX.md': buildIndex(manifest),
    'docs/STATUS.md': buildStatus(state, packet),
    'llms.txt': buildLlms(state, packet),
    ...buildGenerated(manifest, state, packet),
  };
}

export function generateDocs({ check = false } = {}) {
  const outputs = generatedOutputs();
  const drift = [];
  for (const [relativePath, content] of Object.entries(outputs)) {
    if (check) {
      let current = '';
      try {
        current = readText(relativePath);
      } catch {
        current = '';
      }
      if (current !== content) drift.push(relativePath);
    } else {
      writeAtomic(relativePath, content);
    }
  }
  if (check && drift.length) {
    console.error('Generated documentation drift:');
    for (const file of drift) console.error(`- ${file}`);
    process.exitCode = 1;
  } else if (check) {
    console.log(`Generated documentation is current: ${Object.keys(outputs).length} files.`);
  } else {
    console.log(`Generated documentation updated: ${Object.keys(outputs).length} files.`);
  }
  return drift;
}

if (process.argv[1]?.endsWith('generate-docs.mjs')) {
  generateDocs({ check: process.argv.includes('--check') });
}
